sudo: required
language: java
jdk: oraclejdk11

services:
  - postgresql

before_install:
  - cd Backend
  - cd PharmacyProject
  - chmod +x mvnw

addons:
  sonarcloud:
  organization: "aleksandarb99"
  token: $SONAR_TOKEN

script:
  - ./mvnw clean install -DskipTests=false -B
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=aleksandarb99_Apoteka_Projekat


dist: trusty

before-deploy:
- cd ..
- cd ..

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: apotekaprojekat
  on: main
