sudo: required
language: java
jdk: oraclejdk11

services:
  - postgresql

before_install:
  - cd Backend
  - cd PharmacyProject
  - chmod +x mvnw

script:
  - ./mvnw clean install -DskipTests=false -B

dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: apotekaprojekat
