sudo: required
language: java
jdk: oraclejdk11

services:
  - postgresql

before_install:
  - cd Backend
  - cd PharmacyProject
  - chmod +x mvnw

addons:
  sonarcloud:
  organization: "aleksandarb99"
  token: $SONAR_TOKEN

script:
  - ./mvnw clean install -DskipTests=false -B
    - ./mvnw sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=aleksandarb99 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN


dist: trusty

before-deploy:
- cd ..
- cd ..

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: apotekaprojekat
  on: main
